<script>
  import { ScrollSpy } from 'flowbite-svelte';
  
  const items = [
    { id: 'section-1', label: 'Section 1' },
    { id: 'section-2', label: 'Section 2' },
    { id: 'section-3', label: 'Section 3' }
  ];
</script>

<ScrollSpy {items} position="left" />

<section id="section-1">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer non commodo turpis. Pellentesque id mi ex. Nam porttitor leo nec lectus auctor aliquam. Phasellus placerat blandit nulla, sit amet viverra sapien dignissim quis. Etiam et lorem ut leo ultricies volutpat. Praesent sollicitudin purus at tortor pretium facilisis. Cras placerat cursus nisl, eget scelerisque tellus laoreet a.

Nulla vehicula, sapien egestas egestas ultrices, nisi erat venenatis augue, vel sollicitudin est neque nec dui. Aenean risus ex, accumsan ut hendrerit quis, tincidunt quis nulla. Etiam id ipsum sit amet elit egestas interdum a sed metus. Proin semper lobortis turpis, sed ultricies purus condimentum vel. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce hendrerit iaculis sem a tincidunt. Aliquam eget venenatis tellus.

Curabitur vehicula eget tellus ullamcorper tincidunt. Integer eu pulvinar erat. Aenean augue eros, vulputate ut dui et, efficitur tempus metus. Quisque et lobortis nisl, vel semper sem. Mauris vitae gravida libero. Cras erat massa, gravida eget ligula ut, laoreet consequat sem. Sed vehicula ornare purus sit amet aliquam. Quisque fringilla vestibulum tortor, in varius erat vulputate sed. Quisque eleifend turpis eu justo vehicula, ac aliquet orci lacinia. Curabitur vitae aliquam libero. Suspendisse ac quam ex. Nam vitae nibh et erat dignissim lacinia.

Vivamus volutpat tristique lorem viverra sollicitudin. Nullam dapibus, mi eu consectetur tincidunt, massa massa pellentesque ipsum, sit amet scelerisque arcu velit id tellus. Vestibulum id mi vel justo ullamcorper porta. Maecenas dolor diam, lacinia quis sapien sed, maximus molestie arcu. Nam tempus nisl sed tortor vestibulum sagittis. Mauris rutrum odio quis sem volutpat, nec porttitor orci tristique. In in ligula diam. Curabitur aliquet fermentum dui, sed ultricies ipsum vehicula id. Sed dapibus iaculis ornare. Maecenas fermentum magna purus. Nam eu nisl vulputate, interdum ligula eget, faucibus velit. Vestibulum tempus, nunc id consequat mollis, nisl eros faucibus diam, ut egestas purus erat non massa. Proin nec felis vitae ex placerat congue eu ut dolor.

Proin convallis elit eget pharetra porta. Cras urna purus, placerat et cursus non, hendrerit a nisi. Suspendisse quis rhoncus nibh, eu ultricies odio. Duis ornare velit in tellus feugiat, eu accumsan mi ultrices. Cras rhoncus vitae nisl a lacinia. Pellentesque condimentum mi leo, in gravida neque vestibulum quis. Cras in commodo erat. Curabitur rutrum vestibulum pharetra. Integer quis pellentesque quam, non varius mauris. Nam egestas mi eu ligula aliquam egestas. Etiam ex turpis, vehicula vitae dui eu, dapibus interdum arcu.</section>
<section id="section-2">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer non commodo turpis. Pellentesque id mi ex. Nam porttitor leo nec lectus auctor aliquam. Phasellus placerat blandit nulla, sit amet viverra sapien dignissim quis. Etiam et lorem ut leo ultricies volutpat. Praesent sollicitudin purus at tortor pretium facilisis. Cras placerat cursus nisl, eget scelerisque tellus laoreet a.

Nulla vehicula, sapien egestas egestas ultrices, nisi erat venenatis augue, vel sollicitudin est neque nec dui. Aenean risus ex, accumsan ut hendrerit quis, tincidunt quis nulla. Etiam id ipsum sit amet elit egestas interdum a sed metus. Proin semper lobortis turpis, sed ultricies purus condimentum vel. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce hendrerit iaculis sem a tincidunt. Aliquam eget venenatis tellus.

Curabitur vehicula eget tellus ullamcorper tincidunt. Integer eu pulvinar erat. Aenean augue eros, vulputate ut dui et, efficitur tempus metus. Quisque et lobortis nisl, vel semper sem. Mauris vitae gravida libero. Cras erat massa, gravida eget ligula ut, laoreet consequat sem. Sed vehicula ornare purus sit amet aliquam. Quisque fringilla vestibulum tortor, in varius erat vulputate sed. Quisque eleifend turpis eu justo vehicula, ac aliquet orci lacinia. Curabitur vitae aliquam libero. Suspendisse ac quam ex. Nam vitae nibh et erat dignissim lacinia.

Vivamus volutpat tristique lorem viverra sollicitudin. Nullam dapibus, mi eu consectetur tincidunt, massa massa pellentesque ipsum, sit amet scelerisque arcu velit id tellus. Vestibulum id mi vel justo ullamcorper porta. Maecenas dolor diam, lacinia quis sapien sed, maximus molestie arcu. Nam tempus nisl sed tortor vestibulum sagittis. Mauris rutrum odio quis sem volutpat, nec porttitor orci tristique. In in ligula diam. Curabitur aliquet fermentum dui, sed ultricies ipsum vehicula id. Sed dapibus iaculis ornare. Maecenas fermentum magna purus. Nam eu nisl vulputate, interdum ligula eget, faucibus velit. Vestibulum tempus, nunc id consequat mollis, nisl eros faucibus diam, ut egestas purus erat non massa. Proin nec felis vitae ex placerat congue eu ut dolor.

Proin convallis elit eget pharetra porta. Cras urna purus, placerat et cursus non, hendrerit a nisi. Suspendisse quis rhoncus nibh, eu ultricies odio. Duis ornare velit in tellus feugiat, eu accumsan mi ultrices. Cras rhoncus vitae nisl a lacinia. Pellentesque condimentum mi leo, in gravida neque vestibulum quis. Cras in commodo erat. Curabitur rutrum vestibulum pharetra. Integer quis pellentesque quam, non varius mauris. Nam egestas mi eu ligula aliquam egestas. Etiam ex turpis, vehicula vitae dui eu, dapibus interdum arcu.</section>
<section id="section-3">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer non commodo turpis. Pellentesque id mi ex. Nam porttitor leo nec lectus auctor aliquam. Phasellus placerat blandit nulla, sit amet viverra sapien dignissim quis. Etiam et lorem ut leo ultricies volutpat. Praesent sollicitudin purus at tortor pretium facilisis. Cras placerat cursus nisl, eget scelerisque tellus laoreet a.

Nulla vehicula, sapien egestas egestas ultrices, nisi erat venenatis augue, vel sollicitudin est neque nec dui. Aenean risus ex, accumsan ut hendrerit quis, tincidunt quis nulla. Etiam id ipsum sit amet elit egestas interdum a sed metus. Proin semper lobortis turpis, sed ultricies purus condimentum vel. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce hendrerit iaculis sem a tincidunt. Aliquam eget venenatis tellus.

Curabitur vehicula eget tellus ullamcorper tincidunt. Integer eu pulvinar erat. Aenean augue eros, vulputate ut dui et, efficitur tempus metus. Quisque et lobortis nisl, vel semper sem. Mauris vitae gravida libero. Cras erat massa, gravida eget ligula ut, laoreet consequat sem. Sed vehicula ornare purus sit amet aliquam. Quisque fringilla vestibulum tortor, in varius erat vulputate sed. Quisque eleifend turpis eu justo vehicula, ac aliquet orci lacinia. Curabitur vitae aliquam libero. Suspendisse ac quam ex. Nam vitae nibh et erat dignissim lacinia.

Vivamus volutpat tristique lorem viverra sollicitudin. Nullam dapibus, mi eu consectetur tincidunt, massa massa pellentesque ipsum, sit amet scelerisque arcu velit id tellus. Vestibulum id mi vel justo ullamcorper porta. Maecenas dolor diam, lacinia quis sapien sed, maximus molestie arcu. Nam tempus nisl sed tortor vestibulum sagittis. Mauris rutrum odio quis sem volutpat, nec porttitor orci tristique. In in ligula diam. Curabitur aliquet fermentum dui, sed ultricies ipsum vehicula id. Sed dapibus iaculis ornare. Maecenas fermentum magna purus. Nam eu nisl vulputate, interdum ligula eget, faucibus velit. Vestibulum tempus, nunc id consequat mollis, nisl eros faucibus diam, ut egestas purus erat non massa. Proin nec felis vitae ex placerat congue eu ut dolor.

Proin convallis elit eget pharetra porta. Cras urna purus, placerat et cursus non, hendrerit a nisi. Suspendisse quis rhoncus nibh, eu ultricies odio. Duis ornare velit in tellus feugiat, eu accumsan mi ultrices. Cras rhoncus vitae nisl a lacinia. Pellentesque condimentum mi leo, in gravida neque vestibulum quis. Cras in commodo erat. Curabitur rutrum vestibulum pharetra. Integer quis pellentesque quam, non varius mauris. Nam egestas mi eu ligula aliquam egestas. Etiam ex turpis, vehicula vitae dui eu, dapibus interdum arcu.</section>